ProjectWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from results import views,viewslog


urlpatterns = [
             
    url(r'^admin/', admin.site.urls),
    url(r'^home/$', views.index2, name='welcome'), 
    url(r'^welcome/', include('results.urls')),
    url(r'^search/$', views.searh, name='search'),
    url(r'^results/$', views.ajaxstudentresults,name='results'),
    url(r'^$', viewslog.user_login,name='login'),
    url(r'^logout/$', viewslog.logout_view,name='logout'),
    url(r'^register/$',viewslog.register,name='register'), 
     
    
    
]

results/urls.py
'''
Created on Aug 14, 2016

@author: KEVIN
'''
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from results import views, viewslog
from results.views import Greeting, Studentcreate, Studentlist, StudentDetail, DeleteStudent, StudentUpdate, Markcreate


urlpatterns = [
    

    url(r'^index/studentregister/$', views.display),                    
    url(r'^index/$', views.index),                     
    url(r'^display/(?P<id>[\d+]{1})/$', views.display_projectweb),                                           
    url(r'^greeting/$', Greeting.as_view(), name='greeting'),
    url(r'^index1/student_registration/$', views.registrationstudent),
    url(r'^index1/$', views.index1),
    url(r'^stureg/$', views.stureg,name='stureg' ),
    url(r'^stureg/student_registrationclass/$', Studentcreate.as_view(), name='studentcreate'),
    url(r'^stureg/student_list/$',login_required(Studentlist.as_view()), name='studentlist'), 
    url(r'^stureg/studentdetail/(?P<pk>\d+)/$', login_required(StudentDetail.as_view(template_name='studentdetail.html')), name='studentdetail'),  
    url(r'^stureg/deletestudent/(?P<id>\d+)/$', login_required(DeleteStudent.as_view()), name='delete_student'),  
    url(r'^stureg/StudentUpdate/(?P<id>\d+)/$', StudentUpdate.as_view(), name='studentUpdate'),                 
    url(r'^stureg/results/createmarks/$', login_required(Markcreate.as_view()), name='Markcreate'),
     
    url(r'^contact/$', views.contactus, name='contactus'),
    url(r'^test/$', viewslog.test, name='test'),
    url(r'^cookie_demo/$', viewslog.cookie_demo, name='cookie_demo'),
    

       
]

results/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=200)
    city=models.CharField(max_length=200)
    age=models.IntegerField()
    M=1
    F=2
    GENDER=(
            
            (M,'Male'),
            (F,'Female'),
            
            
            )
    gender=models.IntegerField(choices=GENDER,default=M)
    address=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    
    def __str__(self):
        
        return str(self.id)+'-'+ self.name
    
class Marks(models.Model): 
    studentmark=models.ForeignKey(Student,on_delete=models.CASCADE)  
    ENGLISH=1
    MATHS=2
    PHYSICS=3
    SUBJECTS=(
              
            (ENGLISH,'english'),  
             (MATHS,'maths'), 
             (PHYSICS,'physics'),  
               
               
              
              ) 
    subject=models.IntegerField(choices=SUBJECTS)
    marks=models.IntegerField()

results/forms.py
'''
Created on Aug 19, 2016

@author: KEVIN
'''
from django import forms
from django.contrib.auth.models import User
from django.forms.models import ModelForm

from results.models import Student, Marks


class Studentform(ModelForm):
   name=forms.CharField(widget=forms.TextInput(attrs={'style':'border:1px dotted #000000;'})) 
   address=forms.CharField(widget=forms.TextInput(attrs={'style':'border:3px inset #FF2256'}))
    
   class Meta:
        
        model=Student
        
        fields='__all__'
        #fields=( 'name', 'address','age')
class Markform(ModelForm):
   
    
   class Meta:
        
        model=Marks
        
        fields='__all__'
        #fields=( 'name', 'address','age')  
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.CharField(
                        widget=forms.TextInput(attrs={'class': "input"}),)
    class Meta:
        model = User
        fields = ('username', 'email', 'password')        
          

results/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin,\
    PermissionRequiredMixin
from django.db import connection
from django.http.response import HttpResponse
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.utils.decorators import method_decorator
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from results.forms import Studentform, Markform 
from results.models import Student, Marks


# Create your views here.
def dear(request):
    
    return HttpResponse('welcome to django kevin'+request.META['HTTP_USER_AGENT'])



def display(request):
    name=request.GET['name']
    city=request.GET['city']
    age=request.GET['age']
    phone=request.GET['phone']
    email=request.GET['email']
    
    sql="INSERT INTO projectweb.webproject (name, city, age, phone, email) VALUES ('"+name+"','"+city+"','"+age+"','"+phone+"','"+email+"') "
    print(name,city,age,phone,email)
    print sql
    cursor=connection.cursor()
    cursor.execute(sql)
    return HttpResponse(" form uploaded done")


def display_projectweb(request,id):
    sql="select name, city, age, phone, email from webproject where id='"+id+"' "
    cursor=connection.cursor()
    cursor.execute(sql)
    result=cursor.fetchall()
    my_html=''
    for r in result:
        print r
        print my_html
        my_html="<html><head><style>body {background-color: powderblue;}th,td{color:red;}</style></head><body><table border=3><tr><th><label>Name</label></th><td>"+r[0]+"</td></tr><tr><th><label>City</label></th><td>"+r[1]+"</td></tr><tr><th><label>Age</label></th><td>"+str(r[2])+"</td></tr><tr><th><label>Phone</label></th><td>"+str(r[3])+"</td> </tr><tr><th><label>Email</label></th><td>"+r[4]+"</td></tr></table> </body></html>"                                                                                                     
                   
    return HttpResponse(my_html)    
def index(request):
    template='my_form.html'
    data={
    }
    return render_to_response(template,data,RequestContext(request))


def index1(request):
    template='student_registration.html'
    data={'student_form': Studentform() }
    
    return render(request,template,data) 
 
 
 
@login_required    
def registrationstudent(request): 
    
    
    student=Student()  
    student.name=request.POST['name']
    student.city=request.POST['city']
    student.age=request.POST['age']
    student.gender=request.POST['gender']
    student.address=request.POST['address']
    student.phone=request.POST['phone']
    student.save()
    
    return HttpResponse('User successfully registered')   
        
class Greeting(View):
    
    greet='hi man how are you'
    
    
    def get(self,request):
        
        return HttpResponse(self.greet) 
    
@login_required
def index2(request):
    template='welcome.html'
    data={}
    
    return render(request,template,data) 

def searh(request):
    template='search.html'
    data={}
    
    return render(request,template,data) 



@login_required
def stureg(request):
    template='student_registrationclass.html'
    data={'student_form': Studentform() }
    
    return render(request,template,data) 

class Studentcreate(LoginRequiredMixin,CreateView): 
    
    model=Student 
    success_url='/welcome/stureg/student_list/'    
    form_class=Studentform  
  
class Studentlist(PermissionRequiredMixin,ListView): 
    model=Student
    context_object_name='student_list'        
    template_name='student_list.html'
    permission_required='results.change_student'
   
class StudentDetail(DetailView):  
    model=Student 
    #template_name='student_list.html' 
   
class DeleteStudent(DeleteView):  
    model=Student  
    success_url='/welcome/stureg/student_list/'
    
    def get_object(self, queryset=None):
        
        obj=Student.objects.get(id=self.kwargs['id'])
        return obj
  
class StudentUpdate(UpdateView): 
    model=Student
    success_url='/welcome/stureg/student_list/'    
    form_class=Studentform    
    
    def get_object(self, queryset=None):
        
        obj=Student.objects.get(id=self.kwargs['id'])
        return obj 
    
 
class Markcreate(CreateView): 
    
    model=Marks 
    success_url='/welcome/stureg/results/createmarks/'    
    form_class=Markform  
    
def ajaxstudentresults(request): 
    
    if request.is_ajax():
        querry_string=request.GET.get('search_text')
        
        if querry_string is not None:
            results=Marks.objects.filter(studentmark_id=querry_string).order_by('subject')
            try:
                studentmark=Student.objects.get(pk=querry_string)
                studentmark=studentmark.name
                
            except:
                
                studentmark=''
                
            template='results/student_results.html'
            data={
                  
                  'results':results,
                  'student_name':studentmark
                
                  }    
                    
            return render_to_response(template, data, RequestContext(request))
    
def contactus(request):
    
    
    template='contactus.html'
    data={}
    return render(request,template,data) 
    
    
   
    

results/templates/results/marks_form.html
{% extends "base.html"  %} {% block content %}

	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">University Showlist</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			{% include "submenunav.html" %}
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<div class="col-md-3">
				<p class="lead">University</p>
			
				
				{% include "submenu.html" %}
			</div>

			<div class="col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading">Marks Create</div>
					<form id="user_form" method="POST" action="">
						

						{% csrf_token %}
						<!--  {{student_form.as_p}}-->
						<table class="table">
							<tr>
								<th><label>Name</label></th>
								<td>{{form.studentmark}}</td>
							</tr>

							<tr>
								<th><label>Subject</label></th>
								<td>{{form.subject}}</td>
							</tr>
							<tr>
								<th><label>Mark</label></th>
								<td>{{form.marks}}</td>
							</tr>
							
						</table>

						<input class="btn btn-primary" type="submit" name="submit" value="CreateMarks">

					</form>

				</div>

			</div>
			<!-- /.container -->

			<div class="container">

				<hr>

				<!-- Footer -->
				<footer>
					<div class="row">
						<div class="col-lg-12">
							<p>Copyright &copy; Your Website 2014</p>
						</div>
					</div>
				</footer>
			</div>
		</div>
		<!-- /.container -->
{% endblock %}

results/templates/results/student_confirm_delete.html
<!DOCTYPE form PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static "css/university.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" >
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" >
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script >

function permission(){
	var r=confirm("press a button");
	if (r==true){
		document.getElementById("perm").submit();	
	}
	
	else {
		window.location.assign("{% url 'studentlist' %}");
	}
}


</script>
</head>
<body>
<form  id= "perm" action="" method="post">
{% csrf_token %}
<button type="button" class="btn btn-warning" onclick="permission()"> Press Here,Click 'OK' to proceed and 'Cancel' to Quit </button>
<p class="glyphicon glyphicon-hand-left"></p>
<input type="submit" style="display:none;" >  

 <p><a id="myAnchor" href=""></a></p>

</body>
</form>

</html>

results/templates/results/student_form.html
{% extends "base.html"  %} {% block content %}

	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">University Showlist</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			{% include "submenunav.html" %}
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<div class="col-md-3">
				<p class="lead">University</p>
				{% include "submenu.html" %}
			</div>

			<div class="col-md-9">
			<div class="container">
				<div class="panel panel-default">
					<div class="panel-heading">Update List</div>
					<form id="user_form1" method="post" action=""
						class="form-horizontal">
						{% csrf_token %}
						<div class="row">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-2 control label">Name</label>
							<div class="col-sm-10">{{ form.name}}</div>
								
						</div>
						</div>
						<div class="row">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control label">City</label>
							<div class="col-sm-10">{{ form.city}}</div>
						</div>
						</div>
						<div class="row">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control label">Age</label>
							<div class="col-sm-10">{{ form.age}}</div>
							</div>
						</div>
						<div class="row">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control label">Gender</label>
							<div class="col-sm-10">{{ form.gender}}</div>
							</div>
						</div>
						<div class="row">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control label">Address</label>
							<div class="col-sm-10">{{ form.address}}</div>
							</div>
						</div>
						<div class="row">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control label">Phone</label>
							<div class="col-sm-10">{{ form.phone}}</div>
						</div>
						</div>
						<div class="row">
						<div class="form-group">
							<div class="col-sm-push-2"  ></div>
							<input class="col-sm-2" style="position:absolute;left:120px;"class="btn btn-default" type="submit" value="Submit">
					</div>
						</div>
					</form>

				</div>
				</div>
			</div>
			<!-- /.container -->

			<div class="container">

				<hr>

				<!-- Footer -->
				<footer>
					<div class="row">
						<div class="col-lg-12">
							<p>Copyright &copy; Your Website 2014</p>
						</div>
					</div>
				</footer>
			</div>
		</div>
		{% endblock %}

results/templates/results/student_results.html
{% block content %}
{% if student_name != ''%}

<div class="panel panel-default">
	<div class="panel-heading">
		<center>
			<b>Student Name : {{ student_name }}</b>
		</center>
	</div>
	<table class="table table-bordered table-striped">
		<tbody>
			{% for marks in results %}
			<tr class="{% cycle 'odd' 'even' %}">
				<th>{{ marks.get_subject_display }}</th>
				<td class="right">{{ marks.marks }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% else %}
<div class="panel panel-default">
	<div class="panel-heading">
		<center>Student roll number not found</center>
	</div>
</div>
{% endif %}
 {% endblock %}